### PR TITLE
Updated has_gravatar to make a HEAD request

### PR DESCRIPTION
**Pull request by syndbg**
Addresses #18

### CODE REVIEW

**Comment by twaddington** [comment]
Thanks for this pull @syndbg. Unfortunately, tests are failing because you've removed several required Django files (namely `models.py`). These files are required by Django even though they are empty:

```
ImproperlyConfigured: App with label django_gravatar is missing a models.py module.
```

If you can update your pull request by reverting the changes you made to these files tests should be able to be run again.

I also see a number of indentation and formatting changes. Please revert these as well to ensure the pull request only consists of the minimum required code changes.

**Comment by syndbg** [comment]
Restored stub models.py and views.py

However, the formatting changes are to compliment the PEP8 style. If you still don't want them, I will revert them too.

**Comment by twaddington** [comment]
Thanks @syndbg. I see that tests are now passing.

Please do revert the PEP8 fixes. I'm not a fan of some of their indentation rules and whitespace fixes make it harder to identify the actual changes.

**Comment by syndbg** [comment]
:+1:

**Comment by twaddington** [comment]
@syndbg looks great! Thanks for your contribution. I'll get this merged in right now, do a little testing and get a new version up on PyPi later today.

**Pull request merged**
