### PR TITLE
Django 1.10 & 1.11 support

### PR DESCRIPTION
**Pull request by browniebroke**
- [x] Add Django 1.10 & 1.11 to the build matrix
- [x] Fix 1.10 errors
- [x] Fix 1.11 errors

### CODE REVIEW

**Comment by twaddington** [comment]
Thanks @browniebroke! Let me know when this PR is ready and I'll take a look.

I honestly haven't really been using Django much lately. I really appreciate you taking the time to update the build matrix.

**Comment by browniebroke** [comment]
Sure, I'll ping you when it's all green, should be not far now.

**Comment by browniebroke** [comment]
Well, here you go, ready on my end.
Let me know if I could do anything to assist with simplifying your role of maintainer.

**Comment by twaddington** [comment]
Looks good to me.

**Pull request merged**
